import { NextResponse } from 'next/server';
import { GitHubService } from '../../../../lib/github-service';

export async function POST(req) {
  try {
    const { name, description } = await req.json();

    if (!name) {
      return NextResponse.json({ error: 'Repository name is required' }, { status: 400 });
    }

    // Call our library helper
    const newRepo = await GitHubService.createRepo(name, description || "Generated by AI App Builder");

    return NextResponse.json({ 
      success: true, 
      repoUrl: newRepo.html_url,
      repoName: newRepo.full_name
    });

  } catch (error) {
    console.error("Create Repo Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
