import { NextResponse } from 'next/server';
import { getServerSession } from "next-auth";
import { authOptions } from "../../auth/[...nextauth]/route";
import { Octokit } from "@octokit/rest";
import { clientPromise } from "@/lib/db";

export async function POST(req) {
  try {
    const session = await getServerSession(authOptions);
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // 1. Retrieve the User's GitHub Token from the Database
    // (Since we used MongoDBAdapter, the token is stored in the 'accounts' collection)
    const client = await clientPromise;
    const db = client.db();
    
    const account = await db.collection("accounts").findOne({
      userId: session.user.id, // The ID from the session (ObjectId or String)
      provider: "github"
    });

    if (!account || !account.access_token) {
      return NextResponse.json({ error: "GitHub account not connected. Please go to Settings to link it." }, { status: 400 });
    }

    const githubToken = account.access_token;
    const { repoName, files } = await req.json();

    // 2. Initialize Octokit with the USER'S token
    const octokit = new Octokit({ auth: githubToken });

    // 3. Create the Repo (on the User's account)
    // auto_init: true creates a README so we can commit immediately
    const { data: repo } = await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      private: true, // Default to private for safety
      auto_init: true,
      description: "Generated by AppBuild AI"
    });

    // 4. (Simplified) We would loop through files and create commits here.
    // For this demo, we just return success that we created the repo.
    
    return NextResponse.json({ 
      success: true, 
      repoUrl: repo.html_url,
      message: `Repository '${repoName}' created successfully on your GitHub!`
    });

  } catch (error) {
    console.error("GitHub Push Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
