"use client";

import { useState, useEffect } from "react";
import { 
  X, Activity, MapPin, Compass, Wifi, 
  Smartphone, Zap, CheckCircle2 
} from "lucide-react";

export default function SensorBridge({ isOpen, onClose, onUpdateFile, triggerHaptic }) {
  const [data, setData] = useState({ x: 0, y: 0, z: 0, lat: null, lng: null });
  const [isSimulating, setIsSimulating] = useState(false);
  const [activeTab, setActiveTab] = useState('telemetry'); // telemetry | code

  useEffect(() => {
    if (!isOpen) return;

    let motionHandler;
    let geoId;
    let simInterval;

    // 1. Try Real Sensors first
    if (typeof window !== 'undefined' && window.DeviceMotionEvent) {
        motionHandler = (event) => {
            if (event.accelerationIncludingGravity) {
                setData(prev => ({
                    ...prev,
                    x: event.accelerationIncludingGravity.x || 0,
                    y: event.accelerationIncludingGravity.y || 0,
                    z: event.accelerationIncludingGravity.z || 0,
                }));
            }
        };
        window.addEventListener("devicemotion", motionHandler);
    }

    // 2. Try Real GPS
    if (typeof navigator !== 'undefined' && navigator.geolocation) {
        geoId = navigator.geolocation.watchPosition(
            (pos) => {
                setData(prev => ({
                    ...prev,
                    lat: pos.coords.latitude,
                    lng: pos.coords.longitude
                }));
            },
            () => console.log("GPS denied, switching to sim"),
            { enableHighAccuracy: true }
        );
    }

    // 3. Fallback: Desktop Simulation (To make the UI look alive)
    // If no motion is detected after 1s, start simulation
    const checkSensors = setTimeout(() => {
        if (data.x === 0 && data.y === 0) {
            setIsSimulating(true);
            simInterval = setInterval(() => {
                setData(prev => ({
                    x: (Math.random() - 0.5) * 2, // Jitter between -1 and 1
                    y: (Math.random() - 0.5) * 2,
                    z: 9.8 + (Math.random() - 0.5), // Gravity ~9.8
                    lat: 37.7749 + (Math.random() * 0.001),
                    lng: -122.4194 + (Math.random() * 0.001)
                }));
            }, 100);
        }
    }, 1000);

    return () => {
        if (motionHandler) window.removeEventListener("devicemotion", motionHandler);
        if (geoId) navigator.geolocation.clearWatch(geoId);
        if (simInterval) clearInterval(simInterval);
        clearTimeout(checkSensors);
    };
  }, [isOpen]);

  if (!isOpen) return null;

  const handleInject = () => {
    triggerHaptic?.();
    const sensorCode = `
package com.visionary.app.services

import android.hardware.Sensor
import android.hardware.SensorEvent
import android.hardware.SensorEventListener
import android.hardware.SensorManager
import android.util.Log

class SensorBridge : SensorEventListener {
    // GENERATED BY VISIONARY AI
    // Bridges hardware telemetry to UI State

    override fun onSensorChanged(event: SensorEvent?) {
        event?.let {
            val x = it.values[0]
            val y = it.values[1]
            val z = it.values[2]
            Log.d("SensorBridge", "Accelerometer: $x, $y, $z")
            // TODO: Emit to LiveData
        }
    }

    override fun onAccuracyChanged(sensor: Sensor?, accuracy: Int) {
        // Handle accuracy changes
    }
}`;
    onUpdateFile("SensorBridge.kt", sensorCode);
    onClose();
  };

  return (
    <div className="absolute inset-0 z-[100] bg-black/90 backdrop-blur-md flex items-center justify-center p-6 animate-in fade-in duration-200">
      
      {/* Background Ambience */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-green-500/10 rounded-full blur-[120px] pointer-events-none" />

      <div className="w-full max-w-lg bg-black border border-zinc-800 rounded-3xl shadow-2xl overflow-hidden flex flex-col relative z-10">

        {/* HEADER */}
        <div className="h-16 border-b border-zinc-800 flex items-center justify-between px-6 bg-zinc-900/30">
           <div className="flex items-center gap-3">
              <div className="p-2 bg-gradient-to-br from-green-500/20 to-emerald-500/20 rounded-lg border border-green-500/20">
                  <Activity className="w-5 h-5 text-green-400" />
              </div>
              <div>
                  <h3 className="font-bold text-white text-sm tracking-wide">Sensor Bridge™</h3>
                  <p className="text-[10px] text-zinc-500 font-mono uppercase tracking-wider">
                      {isSimulating ? "Simulation Mode Active" : "Hardware Link Active"}
                  </p>
              </div>
           </div>
           <button onClick={onClose} className="p-2 text-zinc-500 hover:text-white transition-colors rounded-lg hover:bg-zinc-800"><X className="w-5 h-5" /></button>
        </div>

        {/* CONTENT */}
        <div className="p-6 space-y-6">

            {/* 1. VISUALIZER */}
            <div className="grid grid-cols-2 gap-4">
                
                {/* ACCELEROMETER CARD */}
                <div className="bg-zinc-900/50 border border-zinc-800 rounded-2xl p-4 relative overflow-hidden group">
                    <div className="flex items-center justify-between mb-4">
                        <span className="text-[10px] font-bold text-zinc-500 uppercase flex items-center gap-1">
                            <Activity className="w-3 h-3" /> Accelerometer
                        </span>
                        <div className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse shadow-[0_0_8px_#22c55e]" />
                    </div>
                    
                    <div className="space-y-2 font-mono text-xs">
                        <div className="flex justify-between items-center">
                            <span className="text-zinc-600">X-AXIS</span>
                            <span className="text-white font-bold">{data.x.toFixed(2)}</span>
                        </div>
                        <div className="w-full h-1 bg-zinc-800 rounded-full overflow-hidden">
                            <div className="h-full bg-red-500 transition-all duration-100" style={{ width: `${Math.min(Math.abs(data.x) * 10, 100)}%` }} />
                        </div>

                        <div className="flex justify-between items-center">
                            <span className="text-zinc-600">Y-AXIS</span>
                            <span className="text-white font-bold">{data.y.toFixed(2)}</span>
                        </div>
                        <div className="w-full h-1 bg-zinc-800 rounded-full overflow-hidden">
                            <div className="h-full bg-green-500 transition-all duration-100" style={{ width: `${Math.min(Math.abs(data.y) * 10, 100)}%` }} />
                        </div>

                        <div className="flex justify-between items-center">
                            <span className="text-zinc-600">Z-AXIS</span>
                            <span className="text-white font-bold">{data.z.toFixed(2)}</span>
                        </div>
                        <div className="w-full h-1 bg-zinc-800 rounded-full overflow-hidden">
                            <div className="h-full bg-blue-500 transition-all duration-100" style={{ width: `${Math.min(Math.abs(data.z) * 10, 100)}%` }} />
                        </div>
                    </div>
                </div>

                {/* GPS CARD */}
                <div className="bg-zinc-900/50 border border-zinc-800 rounded-2xl p-4 relative overflow-hidden flex flex-col justify-between">
                    <div className="flex items-center justify-between mb-2">
                        <span className="text-[10px] font-bold text-zinc-500 uppercase flex items-center gap-1">
                            <MapPin className="w-3 h-3" /> GPS Module
                        </span>
                        <Wifi className="w-3 h-3 text-green-500" />
                    </div>

                    <div className="text-center py-2">
                        <div className="text-2xl font-bold text-white tracking-tighter">
                            {data.lat ? data.lat.toFixed(4) : "WAITING"}
                        </div>
                        <div className="text-[10px] text-zinc-500 font-mono">LATITUDE</div>
                    </div>
                    
                    <div className="text-center py-2 border-t border-zinc-800">
                        <div className="text-2xl font-bold text-white tracking-tighter">
                            {data.lng ? data.lng.toFixed(4) : "WAITING"}
                        </div>
                        <div className="text-[10px] text-zinc-500 font-mono">LONGITUDE</div>
                    </div>
                </div>

            </div>

            {/* 2. DEVICE MOCKUP */}
            <div className="bg-zinc-900/30 border border-zinc-800 rounded-xl p-3 flex items-center gap-4">
                <div className="w-10 h-10 bg-black rounded-lg border border-zinc-700 flex items-center justify-center">
                    <Smartphone className="w-5 h-5 text-zinc-400" />
                </div>
                <div className="flex-1">
                    <h4 className="text-white text-xs font-bold">Hardware Tunnel Established</h4>
                    <p className="text-[10px] text-zinc-500">Streaming raw telemetry to Neural Engine.</p>
                </div>
                <div className="text-[10px] font-mono text-green-500 animate-pulse">
                    ● REC
                </div>
            </div>

            {/* 3. ACTIONS */}
            <button 
                onClick={handleInject}
                className="w-full py-4 bg-gradient-to-r from-green-600 to-emerald-600 hover:opacity-90 text-white font-bold rounded-xl shadow-[0_0_20px_rgba(34,197,94,0.3)] flex items-center justify-center gap-2 active:scale-95 transition-all"
            >
                <Zap className="w-4 h-4 fill-current" /> Inject Sensor Logic
            </button>

        </div>
      </div>
    </div>
  );
}
